### ISSUE TITLE
Azure 체험계정에서는 GPU 지원이 안 되죠??

### ISSUE THREAD

**Issue by theikim** [yunho0130/start-RL#13]
책과는 별도로 Azure에서
https://github.com/tsmatz/minecraft-rl-example
연습해 볼까 하는데

Azure 체험계정에서는 ★GPU가 지원되지 않는거 같네요 ^^
Azure 관련해서 물어볼 곳이 여기 밖에 없네요 ^^
감사합니다.

https://drive.google.com/file/d/12RDtvIGpNM2jAv81cvI3MfrHmKKz4Wkn/view?usp=sharing

**Comment by mystous** [comment]
내용을 찾아 보니 체험계정으로 사용 가능한 가상머신은 B1버스트 가상 머신으로 한정되어 있습니다.

아래 리스트의 가상머신이네요. GPU 지원은 다른 타입의 가상 머신입니다.
https://docs.microsoft.com/ko-kr/azure/virtual-machines/sizes-b-series-burstable

GPU 머신이 꽤 비용이 비싸서 무료로 체험할 수는 없을 것 같습니다. :)
