### ISSUE TITLE
본서 80페이지 Environment 에서 Dependency 오류가 납니다.

### ISSUE THREAD

**Issue by EdgeOfNetwork** [yunho0130/start-RL#15]
해당 레포를 클론하고 environment.yml 을 콘다로 설치 시

하기와 같은 이슈가 발생합니다.

오래된 버전으로 인해 발생한 문제 같은데, 해결법이 있다면 알려주시면 감사하겠습니다.

ResolvePackageNotFound:
  - xz==5.2.4=h1de35cc_4
  - python==3.7.7=hc70fcce_0_cpython
  - libffi==3.2.1=h475c297_4
  - libcxxabi==4.0.1=hcfea43d_1
  - ncurses==6.2=h0a44026_0
  - tk==8.6.8=ha441bb4_0
  - libcxx==4.0.1=hcfea43d_1
  - zlib==1.2.11=h1de35cc_3
  - libedit==3.1.20181209=hb402a30_0
  - readline==8.0=h1de35cc_0
  - openssl==1.1.1e=h1de35cc_0
  - sqlite==3.31.1=ha441bb4_0

**Comment by thecodebliss** [comment]
저도 같은 문제인데 출판사 블로그에는 문의 게시판도 없고 답답하네요. 
답변 부탁합니다.

**Comment by yunho0130** [comment]
현재 Do it! 강화학습 입문은 절판되었으나, 다음과 같은 절차를 통해 누락된 Dependency를 설치하여 해결하실 수 있을 것입니다. 
```
pip install xz==5.2.4
pip install libffi==3.2.1
pip install ncurses==6.2
pip install tk==8.6.8
pip install zlib==1.2.11
pip install libedit==3.1.20181209
pip install readline==8.0
pip install openssl==1.1.1e
pip install sqlite==3.31.1
```
